# Generated by Django 5.1.1 on 2024-09-19 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(13)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=15000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fullName',
            field=models.CharField(default='NoName', max_length=100),
        ),
    ]
