# Generated by Django 5.1.1 on 2024-09-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='player/thumbnails'),
        ),
    ]
