# Generated by Django 5.1.1 on 2024-09-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_song_song_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='crated_on',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='song',
            name='song_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='player/thumbnails'),
        ),
    ]
