# Generated by Django 5.1.1 on 2024-09-24 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_rename_crated_on_song_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
