# Generated by Django 5.1.1 on 2024-09-25 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_alter_song_created_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('playList_thumbnail', models.ImageField(upload_to='player/playlist/thumbnails')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
                ('song', models.ManyToManyField(blank=True, null=True, related_name='songs', to='player.song')),
            ],
        ),
    ]
