# Generated by Django 5.1.1 on 2024-09-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='playList_thumbnail',
            new_name='playlist_thumbnail',
        ),
    ]
