# Generated by Django 5.1.1 on 2024-09-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_song_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='liked',
            new_name='likes',
        ),
    ]
