# Generated by Django 5.1.1 on 2024-09-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_alter_song_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='player/playlist/thumbnails'),
        ),
    ]
