# Generated by Django 5.1.1 on 2024-09-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_playlist_likes_alter_song_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
