# Generated by Django 5.1.1 on 2024-09-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_playlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
