# Generated by Django 5.1.1 on 2024-09-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0016_alter_playlist_slug_alter_playlist_song_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='slug',
        ),
    ]
