# Generated by Django 5.1.1 on 2024-09-28 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0018_playlist_slug_alter_playlist_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='playlist_is_liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(blank=True, related_name='songs', to='player.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='song_is_liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
